### PR TITLE
feat(refactoring): Elasticsearch logfiles assigned as properties

### PR DESCRIPTION
**Pull request by zmarouf**
- :logs => { :general, :indexing_slowlog, :search_slowlow }

### CODE REVIEW

**Comment by Peanutz** [comment]
LGTM.
The directory will have to be changeable at some point too.
Idky but i really like /var/log ... for logs y'know

**Comment by zmarouf** [comment]
That's what :directory_logs is for I guess.
I'm already overriding the log filenames in deploy.

**Comment by Peanutz** [comment]
My bad, just 3lines over your changes KEK

**Comment by Shedna** [comment]
LGTM.

**Pull request merged**
